version: '3.5'

#Docker Networks
networks:
  app-tier:
    # driver: local

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    networks:
      - app-tier  
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
  # app:
  #   image: nextjs-demo-docker
  #   depends_on:
  #     - mysql
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile
  #   volumes:
  #       - .:/app
  #       - /app/node_modules
  #       - /app/.next
  #   # extra_hosts:
  #   #   - "host.docker.internal:172.20.0.2"
  #   ports:
  #     - "3000:3000"
  #   links:
  #     - mysql:mysql
  #   networks:
  #     - app-tier
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"

# Names our volume
volumes:
  my-db:     